# Generated by Django 5.1.1 on 2024-10-08 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxe',
            fields=[
                ('matrikula', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=100)),
                ('modeloa', models.CharField(max_length=100)),
                ('kolorea', models.CharField(max_length=50)),
                ('urtea', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('Dni', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('Telefonoa', models.CharField(max_length=50)),
                ('Jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Alokatu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alokairu_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('itzulketa_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('kotxe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kotxeak.kotxe')),
                ('pertsona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kotxeak.pertsona')),
            ],
        ),
    ]
